model:
name: ConnectorConfig7
#connectortype:
#  name: Utils
#version: 2
connectorproduct:
  name: Custom
  version: 2
connectortypecommands:
- model:
  name: SEND_AUTH_MAIL
  schema: '{"$schema":"http://json-schema.org/draft-04/schema#","$ref":"#/definitions/MailPayload","definitions":{"MailPayload":{"required":["Sender","Body","Receivers","Username","Password","Host"],"properties":{"Sender":{"type":"string"},"Body":{"type":"string"},"Receivers":{"items":{"type":"string"},"type":"array"},"Username":{"type":"string"},"Password":{"type":"string"},"Host":{"type":"string"}},"additionalProperties":false,"type":"object"}}}'
- model:
  name: CREATE_FORM
  schema: '{"$schema":"http://json-schema.org/draft-04/schema#","$ref":"#/definitions/FormPayload","definitions":{"Field":{"required":["Name","HtmlType","Value"],"properties":{"Name":{"type":"string"},"HtmlType":{"type":"string"},"Value":{"additionalProperties":true}},"additionalProperties":false,"type":"object"},"FormPayload":{"required":["Fields"],"properties":{"Fields":{"items":{"$schema":"http://json-schema.org/draft-04/schema#","$ref":"#/definitions/Field"},"type":"array"}},"additionalProperties":false,"type":"object"}}}'
connectortypeevents:
- model:
  name: NEW_APP
  schema: '{"type":"string"}'
# actions:
# - model:
#   name: totoction
#   resource:
#   model:
#   name: totosource
# - model:
#   name: tataction
#   resource: 
#   model:
#   name: tatasource

