model:
name: ConnectorConfig8
#connectortype:
#  name: Workflow
#version: 1
connectorproduct:
  name: Custom
  version: 1
connectortypecommands: []
connectortypeevents: []
actions:
- model:
  name: totoction
  resource:
    model:
    name: totosource
- model:
  name: tataction
  resource:
    model:
    name: tatasource
