model:
  id: 0
  createdat: 0001-01-01T00:00:00Z
  updatedat: 0001-01-01T00:00:00Z
  deletedat: null
name: ConnectorConfig2
connectortypeid: 0
connectortype:
  model:
    id: 2
    createdat: 2020-08-10T15:46:01.043171735+02:00
    updatedat: 2020-08-10T15:46:01.058589841+02:00
    deletedat: null
  name: Workflow
version: 1
connectorproductid: 0
connectorproduct:
  model:
    id: 0
    createdat: 0001-01-01T00:00:00Z
    updatedat: 0001-01-01T00:00:00Z
    deletedat: null
  name: ""
  version: ""
connectortypecommands: []
connectortypeevents: []
connectortypekeys: ""
productkeys: ""
