model:
  id: 0
  createdat: 0001-01-01T00:00:00Z
  updatedat: 0001-01-01T00:00:00Z
  deletedat: null
name: ConnectorConfig1
connectortypeid: 0
connectortype:
  model:
    id: 1
    createdat: 2020-08-10T15:46:01.043171735+02:00
    updatedat: 2020-08-10T15:46:01.058589841+02:00
    deletedat: null
  name: Utils
version: 1
connectorproductid: 0
connectorproduct:
  model:
    id: 0
    createdat: 0001-01-01T00:00:00Z
    updatedat: 0001-01-01T00:00:00Z
    deletedat: null
  name: ""
  version: ""
connectortypecommands:
- model:
    id: 1
    createdat: 2020-08-10T15:46:01.080277396+02:00
    updatedat: 2020-08-10T15:46:01.095985282+02:00
    deletedat: null
  name: SEND_AUTH_MAIL
  schema: '{"$schema":"http://json-schema.org/draft-04/schema#","$ref":"#/definitions/MailPayload","definitions":{"MailPayload":{"required":["Sender","Body","Receivers","Username","Password","Host"],"properties":{"Sender":{"type":"string"},"Body":{"type":"string"},"Receivers":{"items":{"type":"string"},"type":"array"},"Username":{"type":"string"},"Password":{"type":"string"},"Host":{"type":"string"}},"additionalProperties":false,"type":"object"}}}'
- model:
    id: 2
    createdat: 2020-08-10T15:46:01.084112328+02:00
    updatedat: 2020-08-10T15:46:01.096222532+02:00
    deletedat: null
  name: CREATE_FORM
  schema: '{"$schema":"http://json-schema.org/draft-04/schema#","$ref":"#/definitions/FormPayload","definitions":{"Field":{"required":["Name","HtmlType","Value"],"properties":{"Name":{"type":"string"},"HtmlType":{"type":"string"},"Value":{"additionalProperties":true}},"additionalProperties":false,"type":"object"},"FormPayload":{"required":["Fields"],"properties":{"Fields":{"items":{"$schema":"http://json-schema.org/draft-04/schema#","$ref":"#/definitions/Field"},"type":"array"}},"additionalProperties":false,"type":"object"}}}'
connectortypeevents:
- model:
    id: 1
    createdat: 2020-08-10T15:46:01.087800773+02:00
    updatedat: 2020-08-10T15:46:01.096420168+02:00
    deletedat: null
  name: NEW_APP
  schema: '{"type":"string"}'
connectortypekeys: ""
productkeys: ""
